name: Platform API CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

env:
  JAVA_OPTS: -XX:+UseCompactObjectHeaders

jobs:
  run_tests:
    runs-on: Akka-Default-Latest
    steps:
    - name: Checkout Global Scripts
      # https://github.com/actions/checkout/releases
      uses: actions/checkout@v6
      with:
        repository: akka/github-actions-scripts
        path: github-actions-scripts

    - name: Setup global resolver
      run: |
        chmod +x ./github-actions-scripts/setup_global_resolver.sh
        ./github-actions-scripts/setup_global_resolver.sh
        cp -r ./github-actions-scripts ~/

    - name: Checkout
      # https://github.com/actions/checkout/releases
      uses: actions/checkout@v6

    - name: Cache Coursier cache
      # https://github.com/coursier/cache-action/releases
      uses: coursier/cache-action@v8.1.0

    - name: Set up JDK 25
      # https://github.com/coursier/setup-action/releases
      uses: coursier/setup-action@v3.0.0
      with:
        jvm: temurin:1.25
        apps: sbt

    - name: Run tests
      run: sbt "test"
